#version: '3.8'
#services:
#  postgres-db:
#    image: postgres:latest
#    container_name: blogging-db
#    environment:
#      POSTGRES_DB: blogging-db
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#    ports:
#      - "5432:5432"